run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude-functions:
      # Common functions where ignoring errors is acceptable
      - (*os.File).Close
      - (io.Closer).Close
      - (*os/exec.Cmd).Wait
      - (*github.com/spf13/pflag.FlagSet).GetString
      - (*github.com/spf13/pflag.FlagSet).GetBool
      - (*github.com/spf13/pflag.FlagSet).Set
      - encoding/json.MarshalIndent
      - encoding/json.Marshal
      - fmt.Sscanf
      - (*encoding/json.Encoder).Encode
      - syscall.Kill
      - (*os.Process).Kill
  
  govet:
    enable-all: true
    disable:
      - fieldalignment
  
  goimports:
    local-prefixes: github.com/tjboudreaux/queenbee

  misspell:
    locale: US

issues:
  exclude-rules:
    # Allow unused parameters in test files
    - path: _test\.go
      linters:
        - unparam
    
    # Allow unchecked errors in test files (common pattern)
    - path: _test\.go
      linters:
        - errcheck
    
    # Allow dot imports in test files for testify
    - path: _test\.go
      text: "dot-imports"

  max-issues-per-linter: 50
  max-same-issues: 10
